name: CI

on: pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: builld
      uses: CultureHQ/actions-yarn@master
      with:
        args: build

   
